export { default as IHeader } from './IHeader.vue'
export { default as IFooter } from './IFooter.vue'
export { default as ISectionMultiCard } from './ISectionMultiCard.vue'
export { default as ITest } from './ITest.vue'
export { default as IHeaderNewsTop } from './IHeaderNewsTop.vue'
export { default as IHeaderBrand } from './IHeaderBrand.vue'
